platform :ios, '8.0'

target 'sales' do

pod 'AFNetworking', '~> 3.2.1'
pod 'MJExtension', '~> 3.0.15.1'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'SDAutoLayout', '~> 2.2.1'
pod 'SDWebImage', '~> 4.4.2'
pod 'FMDB', '~> 2.7.2'
pod 'DateTools', '~> 2.0.0'
pod 'MJRefresh', '~> 3.1.15.3'
pod 'MLEmojiLabel', '~> 1.0.2'
pod 'MLLabel', '~> 1.10.5'
pod 'LEETheme', '~> 1.1.7'
pod 'Qiniu', '~> 7.2.4'
pod 'JSBadgeView', '~> 1.4.1'
pod 'DKNightVersion', '~> 2.4.3'
pod 'BHBPopView', '~> 1.2.0'
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'DCPathButton', '~> 2.1.4'
pod 'IQKeyboardManager', '~> 6.1.1'
pod 'RongCloudIM', '~> 2.9.4'
pod 'Masonry', '~> 1.1.0'

end
