platform :ios, “8.0”

target ‘sales’ do

pod ‘AFNetworking’, ‘~> 3.1.0’

pod ‘MJExtension’

pod ‘MBProgressHUD’

pod ‘SDAutoLayout’

pod ‘SDWebImage’

pod ‘FMDB’

pod ‘DateTools’

pod ‘MJRefresh’

pod 'MLEmojiLabel'

pod 'MLLabel'

pod 'LEETheme'

pod 'Qiniu'

pod 'RongCloudIMKit'

pod 'JSBadgeView'

pod 'DKNightVersion'

pod 'BHBPopView'

pod 'ASIHTTPRequest'

pod 'DCPathButton'

end
